### ISSUE TITLE
Saving "Opportunities" generates JS errors

### ISSUE THREAD

**Issue by Rio517** [MayOneUS/midas#10]
Editing a Opportunity and clicking save is successful, but generates JS errors and returns a false fail message to the end user.

Perhaps switching to an official release branch will help per https://github.com/MayOneUS/midas/issues/8

![20151008_midas_opportunity_save_js_error](https://cloud.githubusercontent.com/assets/14241/10373775/c5a3e954-6def-11e5-8b8f-b4bfbf485895.png)

**Comment by stevesample** [comment]
What settings on the opportunity caused the error (tags/description/location)? Having some trouble re-creating this one at the moment.

**Comment by Rio517** [comment]
I looked a little more closely and noticed a better error message in some contexts.  I wonder if we're just missing default tags, and those would help us get past these validation errors we're bumping into.

![2015 10 13_save_opportunity_missing_tags](https://cloud.githubusercontent.com/assets/14241/10455369/30b2e33e-71bb-11e5-833f-7773125f0589.png)

**Comment by Rio517** [comment]
`Uncaught TypeError: Cannot read property 'message' of undefined` still happens due to some attempted JS error catching that midas does, but it is no longer blocking users.
