### ISSUE TITLE
Move to MAYDAY live site to a release branch/tag, not on Dev branch.

### ISSUE THREAD

**Issue by Rio517** [MayOneUS/midas#8]
Currently, the site on volunteer.mayday.us is running on a devl branch from the main repo, we should be using the latest public release, not a dev branch.

**Comment by steveslotnick** [comment]
Merged latest changes from devel to master and pushed new tag 0.0.19

**Comment by Rio517** [comment]
We might still be a bit behind the latest public release.  Seem like 18f/midas is up to 0.7.x and 118 commits ahead of our master branch.

**Comment by Rio517** [comment]
I put it all in master and added a tag for 0.7.4.1_mayday - that prod is now serving from.
